/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_udepot_uDepotJNI */

#ifndef _Included_com_ibm_udepot_uDepotJNI
#define _Included_com_ibm_udepot_uDepotJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_udepot_uDepotJNI
 * Method:    init
 * Signature: (Ljava/lang/String;JZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_udepot_uDepotJNI_init
  (JNIEnv *, jobject, jstring, jlong, jboolean);

/*
 * Class:     com_ibm_udepot_uDepotJNI
 * Method:    shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_udepot_uDepotJNI_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_udepot_uDepotJNI
 * Method:    get
 * Signature: ([BJ[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_udepot_uDepotJNI_get
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong);

/*
 * Class:     com_ibm_udepot_uDepotJNI
 * Method:    put
 * Signature: ([BJ[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_udepot_uDepotJNI_put
  (JNIEnv *, jobject, jbyteArray, jlong, jbyteArray, jlong);

/*
 * Class:     com_ibm_udepot_uDepotJNI
 * Method:    del
 * Signature: ([BJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_udepot_uDepotJNI_del
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_ibm_udepot_uDepotJNI
 * Method:    getSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_udepot_uDepotJNI_getSize
  (JNIEnv *, jobject);

/*
 * Class:     com_ibm_udepot_uDepotJNI
 * Method:    getRawDeviceCapacity
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_udepot_uDepotJNI_getRawDeviceCapacity
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
